### ISSUE TITLE
Rider Dark Theme is mixed with Light theme

### ISSUE THREAD

**Issue by eyalist** [JetBrains/rider-theme-pack#19]
After upgrading IntelliJ (and other IDEs like WebStorm), the rider dark theme is mixed with the light one - Some UI elements are dark but the editor section is light:

<img width="1918" alt="bug" src="https://github.com/JetBrains/rider-theme-pack/assets/124697946/7c3dbe86-666f-49b5-860c-bac2fdff6b25">

Tested on:
- IntelliJ IDEA 2023.2 (Ultimate Edition)
  Build #IU-232.8660.185, built on July 26, 2023
- WebStorm 2023.2
  Build #WS-232.8660.143, built on July 21, 2023

**Comment by pkropachev** [comment]
I have the same problem with old UI. All is ok with new UI.

**Comment by pkrakowiak** [comment]
There's an opposite problem, too, where on Rider Day some elements display black backgrounds which makes them illegible.

![obraz](https://github.com/JetBrains/rider-theme-pack/assets/736489/c4d1aa97-2828-4f3a-b73d-5823afb4d84e)

![obraz](https://github.com/JetBrains/rider-theme-pack/assets/736489/b43417c0-4a4e-4b9a-92ef-ba4fb1ed8bb9)

**Comment by oresttokovenkodeel** [comment]
<img width="562" alt="Screenshot 2023-09-26 at 10 44 52 AM" src="https://github.com/JetBrains/rider-theme-pack/assets/143452220/9c1f31ed-df8d-479b-9096-97ab2981db66">

I'm also having this problem after upgrading to Rider UI Theme Pack 0.14.3

**Comment by pkropachev** [comment]
The following workaround helped me solve the problem on my side.

After change the theme, go to `File | Settings | Editor | Color Scheme` and change scheme to the same that specified in `Appearance | Theme`.

![rider-theme](https://github.com/JetBrains/rider-theme-pack/assets/34160907/5dce9a69-21b2-440a-8740-f5c9465b0a3d)

**Comment by oresttokovenkodeel** [comment]
The new Rider Night theme fixed the issue :)

**Comment by homatyano** [comment]
Since recently, IDEA remembers which editor color scheme was last selected for a particular UI theme. So the next time that UI theme is selected, instead of the editor scheme specified by the UI theme, the user preferred editor scheme is loaded instead.

Unfortunately, during the transitional period this caused a number of cases where a wrong editor scheme was selected by the IDE. Meaning, there's nothing wrong with the UI theme or editor scheme, it's just the user preferences were not correctly preserved.

**Comment by drusellers** [comment]
Just hit this again today. Ugh.

**Comment by real-zony** [comment]
I ran into this bug again. Do you have a plan for when it will be fixed?

**Comment by real-zony** [comment]
I encountered this bug again. 😭

**Comment by martin-hirsch** [comment]
Same here <3

**Comment by homatyano** [comment]
Thanks for taking the time to report the issues. It seems the underlying issue was finally resolved: 

https://youtrack.jetbrains.com/issue/RIDER-106580/Errors-while-changing-IDE-theme-in-Rider#focus=Change-27-9386814.0-0

**Comment by martin-hirsch** [comment]
@homatyano, thanks for clarifying! :-) The link seems broken?  aka. "Nope, can't find it!"

**Comment by homatyano** [comment]
@martin-hirsch Sorry I didn't notice the issue was assigned a limited visibility because it contains some private details.

Regarding the issue, the IDE remembers which color scheme was last used with a particular UI theme. Thus, the incorrect scheme will be selected again each time the theme is selected, even though it was selected because of an error in the first place.
